### ISSUE TITLE
introduce - docker-compose 

### ISSUE THREAD

**Issue by alvin-reyes** [alvin-reyes/estuary-docker#2]
# Enhancement Request
Now that we have containerize the nodes, we need to create a docker-compose to spin main estuary with shuttles with a single docker-compose command.

There is a preliminary docker-compose yaml file to do this but there are still a few things to do to complete:

1. grab the auth key from the main estuary
2. assign the generated token to the shuttles

# Possible approach
1 - we can grab the tokens and parse them using regex. We can then assign this as an environment variable for each shuttle.

**Comment by 10d9e** [comment]
A more involved approach could be to have Estuary use vanilla public key encryption to authenticate/authorize users (including configuration of the original admin user). This would decouple admin identity from estuary and allow third party apps to simply log in with their keys. cc @jimmylee @whyrusleeping
